# Generated by Django 5.1.5 on 2025-02-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reservaproduto_reservaservico_delete_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservico',
            name='tempo_duracao',
        ),
    ]
