# Generated by Django 5.1.5 on 2025-02-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
