# Generated by Django 5.1.5 on 2025-02-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_descricao_alter_servico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tempo_duracao',
            field=models.DurationField(),
        ),
    ]
