# Generated by Django 5.1.5 on 2025-02-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servico_tempo_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tempo_duracao',
            field=models.TimeField(),
        ),
    ]
